#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20200720_LinqSuDuomenuBazemis
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CRM")]
	public partial class ConverterDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKlienta(Klienta instance);
    partial void UpdateKlienta(Klienta instance);
    partial void DeleteKlienta(Klienta instance);
    partial void InsertAdresai(Adresai instance);
    partial void UpdateAdresai(Adresai instance);
    partial void DeleteAdresai(Adresai instance);
    #endregion
		
		public ConverterDbDataContext() : 
				base(global::_20200720_LinqSuDuomenuBazemis.Properties.Settings.Default.CRMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConverterDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConverterDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConverterDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConverterDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Klienta> Klientas
		{
			get
			{
				return this.GetTable<Klienta>();
			}
		}
		
		public System.Data.Linq.Table<Adresai> Adresais
		{
			get
			{
				return this.GetTable<Adresai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klientas")]
	public partial class Klienta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Vardas;
		
		private string _Pavarde;
		
		private System.Nullable<System.DateTime> _GimimoDiena;
		
		private string _Email;
		
		private EntitySet<Adresai> _Adresais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVardasChanging(string value);
    partial void OnVardasChanged();
    partial void OnPavardeChanging(string value);
    partial void OnPavardeChanged();
    partial void OnGimimoDienaChanging(System.Nullable<System.DateTime> value);
    partial void OnGimimoDienaChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Klienta()
		{
			this._Adresais = new EntitySet<Adresai>(new Action<Adresai>(this.attach_Adresais), new Action<Adresai>(this.detach_Adresais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vardas", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Vardas
		{
			get
			{
				return this._Vardas;
			}
			set
			{
				if ((this._Vardas != value))
				{
					this.OnVardasChanging(value);
					this.SendPropertyChanging();
					this._Vardas = value;
					this.SendPropertyChanged("Vardas");
					this.OnVardasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavarde", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string Pavarde
		{
			get
			{
				return this._Pavarde;
			}
			set
			{
				if ((this._Pavarde != value))
				{
					this.OnPavardeChanging(value);
					this.SendPropertyChanging();
					this._Pavarde = value;
					this.SendPropertyChanged("Pavarde");
					this.OnPavardeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GimimoDiena", DbType="Date")]
		public System.Nullable<System.DateTime> GimimoDiena
		{
			get
			{
				return this._GimimoDiena;
			}
			set
			{
				if ((this._GimimoDiena != value))
				{
					this.OnGimimoDienaChanging(value);
					this.SendPropertyChanging();
					this._GimimoDiena = value;
					this.SendPropertyChanged("GimimoDiena");
					this.OnGimimoDienaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienta_Adresai", Storage="_Adresais", ThisKey="Id", OtherKey="KlientoId")]
		public EntitySet<Adresai> Adresais
		{
			get
			{
				return this._Adresais;
			}
			set
			{
				this._Adresais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Adresais(Adresai entity)
		{
			this.SendPropertyChanging();
			entity.Klienta = this;
		}
		
		private void detach_Adresais(Adresai entity)
		{
			this.SendPropertyChanging();
			entity.Klienta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adresai")]
	public partial class Adresai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Gatve;
		
		private string _Miestas;
		
		private string _Valstybe;
		
		private string _PastoKodas;
		
		private int _KlientoId;
		
		private EntityRef<Klienta> _Klienta;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGatveChanging(string value);
    partial void OnGatveChanged();
    partial void OnMiestasChanging(string value);
    partial void OnMiestasChanged();
    partial void OnValstybeChanging(string value);
    partial void OnValstybeChanged();
    partial void OnPastoKodasChanging(string value);
    partial void OnPastoKodasChanged();
    partial void OnKlientoIdChanging(int value);
    partial void OnKlientoIdChanged();
    #endregion
		
		public Adresai()
		{
			this._Klienta = default(EntityRef<Klienta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gatve", DbType="NVarChar(25)")]
		public string Gatve
		{
			get
			{
				return this._Gatve;
			}
			set
			{
				if ((this._Gatve != value))
				{
					this.OnGatveChanging(value);
					this.SendPropertyChanging();
					this._Gatve = value;
					this.SendPropertyChanged("Gatve");
					this.OnGatveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miestas", DbType="NVarChar(25)")]
		public string Miestas
		{
			get
			{
				return this._Miestas;
			}
			set
			{
				if ((this._Miestas != value))
				{
					this.OnMiestasChanging(value);
					this.SendPropertyChanging();
					this._Miestas = value;
					this.SendPropertyChanged("Miestas");
					this.OnMiestasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valstybe", DbType="NVarChar(25)")]
		public string Valstybe
		{
			get
			{
				return this._Valstybe;
			}
			set
			{
				if ((this._Valstybe != value))
				{
					this.OnValstybeChanging(value);
					this.SendPropertyChanging();
					this._Valstybe = value;
					this.SendPropertyChanged("Valstybe");
					this.OnValstybeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PastoKodas", DbType="NVarChar(10)")]
		public string PastoKodas
		{
			get
			{
				return this._PastoKodas;
			}
			set
			{
				if ((this._PastoKodas != value))
				{
					this.OnPastoKodasChanging(value);
					this.SendPropertyChanging();
					this._PastoKodas = value;
					this.SendPropertyChanged("PastoKodas");
					this.OnPastoKodasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlientoId", DbType="Int NOT NULL")]
		public int KlientoId
		{
			get
			{
				return this._KlientoId;
			}
			set
			{
				if ((this._KlientoId != value))
				{
					if (this._Klienta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKlientoIdChanging(value);
					this.SendPropertyChanging();
					this._KlientoId = value;
					this.SendPropertyChanged("KlientoId");
					this.OnKlientoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Klienta_Adresai", Storage="_Klienta", ThisKey="KlientoId", OtherKey="Id", IsForeignKey=true)]
		public Klienta Klienta
		{
			get
			{
				return this._Klienta.Entity;
			}
			set
			{
				Klienta previousValue = this._Klienta.Entity;
				if (((previousValue != value) 
							|| (this._Klienta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Klienta.Entity = null;
						previousValue.Adresais.Remove(this);
					}
					this._Klienta.Entity = value;
					if ((value != null))
					{
						value.Adresais.Add(this);
						this._KlientoId = value.Id;
					}
					else
					{
						this._KlientoId = default(int);
					}
					this.SendPropertyChanged("Klienta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
