// <auto-generated />
namespace _20200723_EFCodeFirstDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PridetasAdresas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PridetasAdresas));
        
        string IMigrationMetadata.Id
        {
            get { return "202007231634173_PridetasAdresas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
