//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20200723_EFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Pavadinimas { get; set; }
        public string Tekstas { get; set; }
        public Nullable<System.DateTime> IrasoData { get; set; }
        public string Rasytojas { get; set; }
    }
}
